language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements.txt
  - cd ..
  - django-admin startproject --template=./edge --extension=py,md,html,env wugsy
  - cd wugsy/src
  - cp wugsy/settings/local.sample.env wugsy/settings/local.env
  - python manage.py migrate
script:
  - python manage.py test profiles
