version: '3'

services:
    db:
        environment:
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: password
        restart: always
        image: mysql:latest
        hostname: wugsy_db_1
        volumes:
            - ./mysql_dump:/docker-entrypoint-initdb.d
        networks:
            - esnet
        ports:
          - 3306:3306
    web:
        image: wugsy:latest
        build:
            context: .
            dockerfile: Dockerfile.web
        command: python3 src/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
    fuseki:
        image: stain/jena-fuseki:3.4.0
        ports:
            - "3030:3030"
    elasticsearch: 
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
            - cluster.name=exploreat
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
        ports:
            - 9200:9200
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        networks:
            - esnet

    kibana:
        image: docker.elastic.co/kibana/kibana-oss:6.2.2
        container_name: kibana
        hostname: kibana
        links:
            - elasticsearch
            - db
        ports:
            - 5601:5601
        networks:
            - esnet
    indexer:
        build: 
            context: indexer
            dockerfile: Dockerfile.indexer
        image: python:3.6-slim
        restart: always
        volumes:
            - ./indexer:/app
            - ${TEI_DIR}:/app/data
        depends_on:
            - elasticsearch
        networks:
            - esnet
        container_name: indexer
        command: tail -f /dev/null

volumes:
  esdata:
    driver: local
  

networks:
    esnet:
